version: 0.2
env:
  variables:
    ECR_REPO: 928052840712.dkr.ecr.us-east-2.amazonaws.com/spacy-image
phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - systemctl start docker
      - chmod 666 /run/docker.sock
      - echo "Building a Docker image.."
      - docker build -t myimage . 
      - echo "Tagging Docker image for ECR.."
      - docker tag myImage ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - echo "Logging into ECR.."
      - $(aws ecr get-login --no-include-email)
      - echo "Pushing Docker image to ECR.."
      - docker push ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - echo "Done."
