apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:   
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: deployondocker.azurecr.io/kirti-python-docker:112
        name: python
        ports:
        - containerPort: 8080
