apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cicd-demo
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/components: backend
    app.kubernetes.io/managed-by: kubectl
  name: cicd-demo
spec:
  selector:
    app: cicd-demo
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort:80
